[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter-adventlang = { path = "../tree-sitter-adventlang" }
regex = "1.11.1"
either = "1.15.0"
tree-sitter = "0.25.10"
fxhash = "0.2.1"
test-case = "3.3.1"
thiserror = "2.0.17"
