[package]
name = "type_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
im = "15.1.0"
parser = { path = "../parser" }
fxhash = "0.2.1"
ena = "0.14.3"
tree-sitter = "0.25.10"
thiserror = "2.0.17"
