id = "adventlang"
name = "Adventlang"
version = "0.0.1"
schema_version = 1
authors = ["Kelley van Evert <hello@klve.nl>"]
description = "Adventlang language support for Zed"
repository = "https://github.com/kelleyvanevert/adventlang"

[grammars.adventlang]
repository = "https://github.com/kelleyvanevert/adventlang"
rev = "58e0cd30ec20434ff92d66bd179edaf55721c556"
path = "tree-sitter-adventlang"
